### PR TITLE
change iob_sp_ram_be module to support memories with and wihout BYTE_EN

### PR DESCRIPTION
**Pull request by JDLopes**

### CODE REVIEW

**Comment by jjts** [comment]
Looks clean but shouldn't BYTE_EN be a parameter as in the same system there may be mems with and without byte enables?

**Comment by JDLopes** [comment]
> Looks clean but shouldn't BYTE_EN be a parameter as in the same system there may be mems with and without byte enables?

I don't think so. The BYTE_EN feature is present or not on the platform chosen to implement the circuit. All Xilinx memories support BYTE_EN, as MEMAKER memories do, and all Intel memories do not support BYTE_EN. I don't see the need to use memories that use BYTE_EN and other memories that do not use it on the same circuit.

**Comment by jjts** [comment]
agreed, please change name to MEM_BYTE_EN

**Comment by JDLopes** [comment]
> agreed, please change name to MEM_BYTE_EN

Done!

**Pull request merged**
